suricata_version: 3.1

dependencies:
  - oinkmaster
  - libpcre3
  - libpcre3-dbg
  - libpcre3-dev
  - build-essential
  - autoconf
  - automake
  - libtool
  - libpcap-dev
  - libnet1-dev
  - libyaml-0-2
  - libyaml-dev
  - zlib1g
  - zlib1g-dev
  - libcap-ng-dev
  - libcap-ng0
  - make
  - libmagic-dev
  - libjansson-dev
  - libjansson4
  - pkg-config
  - libnetfilter-queue-dev
  - libnetfilter-queue1
  - libnfnetlink-dev
  - libnfnetlink0
  - libnss3-dev
  - libnspr4-dev
