---
swan_version: 3.17

dependencies:
  - xl2tpd
  - ppp
  - lsof
  - iproute2
  - gawk
  - xmlto # no install recommends
  - libnss3-dev
  - libnspr4-dev
  - pkg-config
  - libpam0g-dev
  - libcap-ng-dev
  - libcap-ng-utils
  - libselinux1-dev
  - libcurl4-nss-dev
  - libgmp3-dev
  - flex
  - bison
  - gcc
  - make
  - libunbound-dev
  - libnss3-tools
  - libevent-dev
