---
- name: install dependencies
  apt:
    name: "{{ item }}"
  with_items: "{{ dependencies }}"

- name: configure squid
  copy:
    src: squid.conf
    dest: /etc/squid3/squid.conf

- name: configure squid
  copy:
    src: squidGuard.conf
    dest: /etc/squidguard/squidGuard.conf
